# Sanity checks for the agent-template catalogue and the bundled
# spike-ramp scenario. These are documentation-shaped assets, so the
# tests only enforce structural invariants — not semantics.
from __future__ import annotations

import json
import re
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
TEMPLATES_DIR = REPO_ROOT / "agent_templates"
CATALOG_JSON = TEMPLATES_DIR / "catalog.json"
SPIKE_SCENARIO = REPO_ROOT / "deploy" / "hermes" / "scenarios" / "spike-ramp.json"

# The catalogue's README table lists these — every one must exist as a
# real markdown file. Guarantees the table doesn't drift silently.
LEGACY_FINANCE_TEMPLATES: tuple[str, ...] = (
    "market_research_analyst",
    "fundamental_analyst",
    "macro_context_agent",
    "bull_bear_debate_pair",
    "risk_committee",
    "memory_reflector",
)

LIFECYCLE_CATEGORIES: tuple[str, ...] = (
    "intake",
    "market-research",
    "mvs",
    "validation",
    "scaling",
    "investor-deliverable",
    "finance",
)

OPS_CATEGORIES: tuple[str, ...] = (
    "sales",
    "deals",
    "marketing",
    "operations",
    "intelligence",
    "customer",
    "back-office",
    "verticals",
)

ALL_CATEGORIES = LIFECYCLE_CATEGORIES + OPS_CATEGORIES + ("skills",)

REQUIRED_FRONTMATTER_FIELDS: frozenset[str] = frozenset(
    {
        "id",
        "name",
        "artifact_type",
        "lifecycle",
        "category",
        "verticals",
        "depends_on",
        "produces",
        "tools",
        "tags",
        "gate",
        "optional",
    }
)

ALLOWED_ARTIFACT_TYPES: frozenset[str] = frozenset({"agent", "sidecar", "skill"})
ALLOWED_LIFECYCLES: frozenset[str] = frozenset({"project", "ops", "both", "none"})
ALLOWED_ROLLOUT_STAGES: frozenset[str] = frozenset(
    {"1-foundation", "2-capture", "3-generate", "4-orchestrate"}
)
ALLOWED_AUTONOMY: frozenset[str] = frozenset(
    {"human-led", "human-assisted", "fully-autonomous"}
)
ALLOWED_OPS_DOMAINS: frozenset[str] = frozenset(
    {"sales", "deals", "marketing", "operations", "intelligence", "customer", "back-office"}
)

ALLOWED_ROLES: frozenset[str] = frozenset(
    {
        "analyst", "judge", "debater", "reflector", "coordinator", "writer",
        "reviewer", "integrator", "worker", "connector", "classifier",
    }
)

ALLOWED_MODES: frozenset[str] = frozenset(
    {
        "single-shot", "debate", "pipeline-stage", "gate", "reflector",
        "streaming", "scheduled", "event-driven",
    }
)


def _iter_cards() -> list[tuple[Path, dict]]:
    out: list[tuple[Path, dict]] = []
    for path in sorted(TEMPLATES_DIR.rglob("*.md")):
        if path.name in {"README.md", "_schema.md"}:
            continue
        text = path.read_text(encoding="utf-8")
        m = re.match(r"^---\n(.*?)\n---\n", text, flags=re.DOTALL)
        if not m:
            continue
        fm = yaml.safe_load(m.group(1))
        assert isinstance(fm, dict), f"frontmatter is not a mapping: {path}"
        out.append((path, fm))
    return out


ALL_CARDS = _iter_cards()


def _lifecycle_cards() -> list[tuple[Path, dict]]:
    return [(p, fm) for p, fm in ALL_CARDS if fm.get("lifecycle") in {"project", "both", "none"}]


def _ops_cards() -> list[tuple[Path, dict]]:
    return [(p, fm) for p, fm in ALL_CARDS if fm.get("lifecycle") in {"ops", "both"}]


def _pipeline_cards() -> list[tuple[Path, dict]]:
    return [(p, fm) for p, fm in ALL_CARDS if fm.get("lifecycle") == "project"]


# ---------------------------------------------------------------------
# Presence / structure
# ---------------------------------------------------------------------

def test_catalogue_is_nonempty() -> None:
    assert ALL_CARDS, "no templates found — the catalogue is empty"


def test_templates_readme_exists() -> None:
    assert (TEMPLATES_DIR / "README.md").is_file()


def test_schema_doc_exists() -> None:
    assert (TEMPLATES_DIR / "_schema.md").is_file()


def test_catalog_json_exists() -> None:
    assert CATALOG_JSON.is_file(), "catalog.json should be regenerated by build_agent_templates_index.py"


@pytest.mark.parametrize("name", LEGACY_FINANCE_TEMPLATES)
def test_legacy_finance_templates_still_exist(name: str) -> None:
    path = TEMPLATES_DIR / "finance" / f"{name}.md"
    assert path.is_file(), f"missing template: {path}"


# ---------------------------------------------------------------------
# Frontmatter — required fields, enums
# ---------------------------------------------------------------------

@pytest.mark.parametrize(
    "path,fm",
    ALL_CARDS,
    ids=[fm["id"] for _, fm in ALL_CARDS],
)
def test_every_card_has_required_frontmatter_fields(path: Path, fm: dict) -> None:
    missing = REQUIRED_FRONTMATTER_FIELDS - fm.keys()
    assert not missing, f"{path} is missing frontmatter fields: {missing}"


@pytest.mark.parametrize(
    "path,fm",
    ALL_CARDS,
    ids=[fm["id"] for _, fm in ALL_CARDS],
)
def test_every_card_has_required_body_sections(path: Path, fm: dict) -> None:
    body = path.read_text(encoding="utf-8")
    for section in ("## Identity", "## Purpose", "## Wiring"):
        assert section in body, f"{path} is missing section {section}"


def test_artifact_type_enum() -> None:
    for path, fm in ALL_CARDS:
        assert fm["artifact_type"] in ALLOWED_ARTIFACT_TYPES, (
            f"{path}: artifact_type {fm['artifact_type']!r} not allowed"
        )


def test_lifecycle_enum() -> None:
    for path, fm in ALL_CARDS:
        assert fm["lifecycle"] in ALLOWED_LIFECYCLES, (
            f"{path}: lifecycle {fm['lifecycle']!r} not allowed"
        )


def test_category_enum() -> None:
    for path, fm in ALL_CARDS:
        assert fm["category"] in ALL_CATEGORIES, (
            f"{path}: category {fm['category']!r} not in {ALL_CATEGORIES}"
        )


def test_verticals_is_list_and_nonempty() -> None:
    for path, fm in ALL_CARDS:
        verticals = fm.get("verticals")
        assert isinstance(verticals, list) and verticals, (
            f"{path}: verticals must be a non-empty list"
        )


def test_ids_are_unique_globally() -> None:
    ids = [fm["id"] for _, fm in ALL_CARDS]
    dups = {i for i in ids if ids.count(i) > 1}
    assert not dups, f"duplicate template ids: {dups}"


def test_id_matches_filename() -> None:
    for path, fm in ALL_CARDS:
        assert fm["id"] == path.stem, (
            f"{path}: id {fm['id']!r} != filename stem {path.stem!r}"
        )
        assert fm["name"] == fm["id"], (
            f"{path}: name {fm['name']!r} != id {fm['id']!r}"
        )


# ---------------------------------------------------------------------
# Ops-axis enforcement
# ---------------------------------------------------------------------

def test_ops_cards_populate_ops_axis() -> None:
    for path, fm in _ops_cards():
        assert fm.get("domain") in ALLOWED_OPS_DOMAINS, (
            f"{path}: ops card must set domain to one of {ALLOWED_OPS_DOMAINS}"
        )
        assert fm.get("rollout_stage") in ALLOWED_ROLLOUT_STAGES, (
            f"{path}: ops card must set rollout_stage"
        )
        assert fm.get("autonomy") in ALLOWED_AUTONOMY, (
            f"{path}: ops card must set autonomy"
        )
        mat = fm.get("maturity")
        assert isinstance(mat, int) and 1 <= mat <= 4, (
            f"{path}: ops card maturity must be int in [1, 4]"
        )


def test_lifecycle_cards_null_ops_fields() -> None:
    # Project + none lifecycle cards must not carry an ops axis.
    for path, fm in _lifecycle_cards():
        for field in ("domain", "rollout_stage", "autonomy", "maturity"):
            assert fm.get(field) is None, (
                f"{path}: lifecycle card must have {field}=null (got {fm.get(field)!r})"
            )


# ---------------------------------------------------------------------
# Role / mode by artifact type
# ---------------------------------------------------------------------

def test_agent_and_sidecar_roles_and_modes() -> None:
    for path, fm in ALL_CARDS:
        if fm["artifact_type"] == "skill":
            continue  # skills may have role=null / mode=null
        role = fm.get("role")
        mode = fm.get("mode")
        assert role in ALLOWED_ROLES, f"{path}: role {role!r} not allowed"
        assert mode in ALLOWED_MODES, f"{path}: mode {mode!r} not allowed"


def test_skills_have_null_role_and_mode() -> None:
    for path, fm in ALL_CARDS:
        if fm["artifact_type"] == "skill":
            assert fm.get("role") is None, f"{path}: skill role must be null"
            assert fm.get("mode") is None, f"{path}: skill mode must be null"


# ---------------------------------------------------------------------
# Pipeline invariants — apply only to lifecycle=project non-finance cards
# ---------------------------------------------------------------------

def test_pipeline_steps_are_unique_and_contiguous() -> None:
    pipeline = [
        fm for _, fm in _pipeline_cards()
        if fm.get("category") != "finance" and isinstance(fm.get("step"), int)
    ]
    steps = [fm["step"] for fm in pipeline]
    assert steps, "no pipeline cards found"
    assert len(set(steps)) == len(steps), f"duplicate steps: {steps}"
    assert min(steps) == 0
    assert set(steps) == set(range(min(steps), max(steps) + 1)), (
        "pipeline steps must be contiguous"
    )


def test_finance_cards_have_no_pipeline_step() -> None:
    for path, fm in ALL_CARDS:
        if fm.get("category") == "finance":
            assert fm.get("step") is None, (
                f"{path}: finance card must have step=null"
            )


def test_ops_cards_have_no_pipeline_step() -> None:
    for path, fm in _ops_cards():
        assert fm.get("step") is None, (
            f"{path}: ops card must have step=null"
        )
        assert fm.get("phase") is None, (
            f"{path}: ops card must have phase=null"
        )


def test_depends_on_references_are_valid() -> None:
    ids = {fm["id"] for _, fm in ALL_CARDS}
    for path, fm in ALL_CARDS:
        for ref in fm.get("depends_on") or []:
            assert ref in ids, f"{path}: depends_on references unknown template {ref!r}"


def test_pipeline_dependencies_point_backwards() -> None:
    # A step-N pipeline template must not depend on a step >= N.
    by_id = {fm["id"]: fm for _, fm in ALL_CARDS}
    for path, fm in _pipeline_cards():
        if fm.get("category") == "finance":
            continue
        if not isinstance(fm.get("step"), int):
            continue
        for ref in fm.get("depends_on") or []:
            upstream = by_id[ref]
            if not isinstance(upstream.get("step"), int):
                continue
            assert upstream["step"] < fm["step"], (
                f"{path}: depends on {ref} (step {upstream['step']}) "
                f"which is not earlier than self (step {fm['step']})"
            )


def test_gate_flag_only_on_gate_mode_templates() -> None:
    for path, fm in ALL_CARDS:
        if fm.get("gate") is True:
            assert fm.get("mode") == "gate", f"{path}: gate=true requires mode=gate"


# ---------------------------------------------------------------------
# README + catalog.json consistency
# ---------------------------------------------------------------------

def test_readme_lists_every_template() -> None:
    body = (TEMPLATES_DIR / "README.md").read_text(encoding="utf-8")
    for _, fm in ALL_CARDS:
        assert f"`{fm['id']}`" in body, (
            f"README does not reference template {fm['id']!r}"
        )


def test_catalog_json_is_wellformed_and_covers_every_card() -> None:
    payload = json.loads(CATALOG_JSON.read_text(encoding="utf-8"))
    assert payload["version"] == "0.13.1"
    assert payload["total"] == len(ALL_CARDS)
    ids_in_json = {c["id"] for c in payload["cards"]}
    ids_on_disk = {fm["id"] for _, fm in ALL_CARDS}
    missing = ids_on_disk - ids_in_json
    extra = ids_in_json - ids_on_disk
    assert not missing, f"catalog.json missing cards: {missing}"
    assert not extra, f"catalog.json has extra cards: {extra}"
    # Every card in the JSON must carry a path pointing at a real file.
    for c in payload["cards"]:
        assert (TEMPLATES_DIR / c["path"]).is_file(), (
            f"catalog.json path missing on disk: {c['path']}"
        )


def test_catalog_json_indexes_are_complete() -> None:
    payload = json.loads(CATALOG_JSON.read_text(encoding="utf-8"))
    for key in (
        "by_artifact_type", "by_lifecycle", "by_category", "by_domain",
        "by_rollout_stage", "by_autonomy", "by_role", "by_mode",
        "by_verticals", "by_tag",
    ):
        assert key in payload["indexes"], f"catalog.json missing index {key}"


# ---------------------------------------------------------------------
# Spike scenario (unchanged from v0.12.x)
# ---------------------------------------------------------------------


def test_spike_scenario_is_wellformed_json() -> None:
    payload = json.loads(SPIKE_SCENARIO.read_text(encoding="utf-8"))
    assert isinstance(payload, dict)
    assert "steps" in payload and "workflow" in payload


def test_spike_scenario_is_monotonically_increasing() -> None:
    payload = json.loads(SPIKE_SCENARIO.read_text(encoding="utf-8"))
    rates = [step["ratePerSecond"] for step in payload["steps"]]
    assert rates == sorted(rates)
    assert rates[0] < rates[-1], "spike scenario should ramp, not plateau"
    assert rates[-1] >= 100, "top step should be a real spike (>=100 wf/s)"


def test_spike_scenario_workflow_matches_taskqueue_convention() -> None:
    payload = json.loads(SPIKE_SCENARIO.read_text(encoding="utf-8"))
    assert payload["workflow"]["taskQueue"] == "temporal-basic"
    assert payload["workflow"]["args"]["sequenceCount"] >= 1
