"""Cloud provisioners for Fly.io and Hetzner Cloud.

Both provisioners run in **dry-run mode** by default. Their job is not to
touch the cloud provider directly — that requires the user's own API tokens,
which we deliberately never carry in Console memory. Instead they:

  1. Write the same `docker-compose.yml` used by the local deployer, so
     `docker compose up -d` on any Ubuntu box (Hetzner VM) or `fly launch`
     (Fly) can reuse it.
  2. Write a provider-specific config file — `fly.toml` for Fly, an
     `hcloud-server.tfvars.example` for Hetzner — with placeholders for
     secrets referenced as ${VAR}.
  3. Return a `PlaybookInputs` dataclass consumed by handoff_playbook.py to
     stitch together the human-readable `nexus.handoff.md`.

The actual `fly deploy` / `hcloud server create` commands live in the
playbook, not in Python. Console never executes them; the user (or a
downstream setup agent like Cloud Cowork / OpenClaw) does, with their
own credentials.
"""

from __future__ import annotations

import secrets
from dataclasses import dataclass, field
from pathlib import Path
from uuid import UUID

from app.core.config import settings


# ────────────────────────────────────────────────────────────────
# Shared compose template — same for local, Fly and Hetzner.
# ────────────────────────────────────────────────────────────────

_COMPOSE_TEMPLATE = """version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: ${{POSTGRES_PASSWORD}}
      POSTGRES_DB: nexus
    volumes:
      - pg_data:/var/lib/postgresql/data

  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:latest
    restart: unless-stopped

  platform:
    image: {image}
    restart: unless-stopped
    depends_on: [postgres, kokoro]
    environment:
      PLATFORM_DATABASE_URL: postgresql+psycopg://nexus:${{POSTGRES_PASSWORD}}@postgres:5432/nexus
      PLATFORM_BOOTSTRAP_TOKEN: ${{PLATFORM_BOOTSTRAP_TOKEN}}
      KOKORO_URL: http://kokoro:8880
    ports:
      - "{port}:8000"

volumes:
  pg_data:
"""


# ────────────────────────────────────────────────────────────────
# Playbook inputs (consumed by handoff_playbook.py)
# ────────────────────────────────────────────────────────────────

@dataclass
class PlaybookInputs:
    """Everything the handoff playbook needs to render.

    Provider-specific commands are provided as ordered lists so the playbook
    can lay them out step by step. Placeholders like ${FLY_API_TOKEN} MUST
    stay literal — they get resolved from `nexus.secrets.env` at deploy time.
    """
    instance_id: UUID
    instance_name: str
    modality: str
    region: str | None
    domain: str | None
    deployments_dir: Path
    endpoint_hint: str

    required_secrets: list[str] = field(default_factory=list)
    provider_steps: list[dict] = field(default_factory=list)
    post_deploy_checks: list[str] = field(default_factory=list)


# ────────────────────────────────────────────────────────────────
# Fly.io provisioner
# ────────────────────────────────────────────────────────────────

_FLY_TOML_TEMPLATE = """# fly.toml — Nexus Platform on Fly.io
# Generated by Console for instance {instance_id} ({instance_name}).
# Secrets referenced with ${{VAR}} MUST come from nexus.secrets.env.

app = "{app_name}"
primary_region = "{region}"

[build]
  image = "{image}"

[env]
  KOKORO_URL = "http://kokoro.internal:8880"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "requests"
    hard_limit = 100
    soft_limit = 80

# Postgres is provisioned separately via `fly postgres create` and attached
# with `fly postgres attach`. The attach step writes DATABASE_URL to secrets.
# Kokoro sidecar is a second Fly app in the same org — see the playbook.
"""


def provision_fly(
    instance_id: UUID,
    instance_name: str,
    region: str | None = None,
    domain: str | None = None,
) -> tuple[Path, str, PlaybookInputs]:
    """Write fly.toml + docker-compose.yml (for reference) + return playbook inputs."""
    dir_ = _instance_dir(instance_id)
    token = secrets.token_urlsafe(32)
    resolved_region = region or "mad"  # Madrid, close to Rodrigo
    app_name = f"nexus-{_short_id(instance_id)}"

    fly_toml = _FLY_TOML_TEMPLATE.format(
        instance_id=instance_id,
        instance_name=instance_name,
        app_name=app_name,
        region=resolved_region,
        image=settings.local_platform_image,
    )
    (dir_ / "fly.toml").write_text(fly_toml, encoding="utf-8")

    # docker-compose.yml is still written for reference (some users prefer
    # to run Fly with `fly deploy --local-only` against a compose file).
    _write_compose(dir_)
    _write_env_placeholders(dir_, token)

    inputs = PlaybookInputs(
        instance_id=instance_id,
        instance_name=instance_name,
        modality="fly",
        region=resolved_region,
        domain=domain,
        deployments_dir=dir_,
        endpoint_hint=domain or f"https://{app_name}.fly.dev",
        required_secrets=[
            "FLY_API_TOKEN",
            "PLATFORM_BOOTSTRAP_TOKEN",
            "POSTGRES_PASSWORD",
            "ANTHROPIC_API_KEY",
        ],
        provider_steps=[
            {
                "title": "Authenticate flyctl",
                "cmd": "fly auth token ${FLY_API_TOKEN}",
            },
            {
                "title": "Launch the app (no deploy yet)",
                "cmd": f"fly launch --name {app_name} --region {resolved_region} --no-deploy --copy-config",
            },
            {
                "title": "Provision managed Postgres",
                "cmd": f"fly postgres create --name {app_name}-db --region {resolved_region} --initial-cluster-size 1",
            },
            {
                "title": "Attach Postgres (writes DATABASE_URL secret automatically)",
                "cmd": f"fly postgres attach --app {app_name} {app_name}-db",
            },
            {
                "title": "Set application secrets (${VAR} come from nexus.secrets.env)",
                "cmd": f"fly secrets set --app {app_name} "
                       f"PLATFORM_BOOTSTRAP_TOKEN=${{PLATFORM_BOOTSTRAP_TOKEN}} "
                       f"ANTHROPIC_API_KEY=${{ANTHROPIC_API_KEY}}",
            },
            {
                "title": "Deploy Kokoro sidecar as a separate Fly app",
                "cmd": f"fly launch --image ghcr.io/remsky/kokoro-fastapi-cpu:latest "
                       f"--name {app_name}-kokoro --region {resolved_region} --now",
            },
            {
                "title": "Deploy Platform",
                "cmd": f"fly deploy --app {app_name}",
            },
        ],
        post_deploy_checks=[
            f"curl -fsSL https://{app_name}.fly.dev/_health  # expect: {{\"status\":\"ok\"}}",
            f"curl -fsSL https://{app_name}.fly.dev/_voice/health  # expect: configured=true",
        ],
    )
    return dir_, token, inputs


# ────────────────────────────────────────────────────────────────
# Hetzner Cloud provisioner
# ────────────────────────────────────────────────────────────────

_CLOUD_INIT_TEMPLATE = """#cloud-config
# Nexus Platform on Hetzner Cloud — cloud-init user-data.
# Generated by Console for instance {instance_id} ({instance_name}).

package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose-v2

write_files:
  - path: /opt/nexus/docker-compose.yml
    permissions: '0644'
    content: |
{compose_indented}
  - path: /opt/nexus/.env
    permissions: '0600'
    content: |
      # Values below are placeholders — the provisioner MUST rewrite this file
      # with the real secrets from nexus.secrets.env before starting Compose.
      PLATFORM_BOOTSTRAP_TOKEN=${{PLATFORM_BOOTSTRAP_TOKEN}}
      POSTGRES_PASSWORD=${{POSTGRES_PASSWORD}}
      ANTHROPIC_API_KEY=${{ANTHROPIC_API_KEY}}

runcmd:
  - systemctl enable --now docker
  - cd /opt/nexus && docker compose up -d
"""


def provision_hetzner(
    instance_id: UUID,
    instance_name: str,
    region: str | None = None,
    domain: str | None = None,
) -> tuple[Path, str, PlaybookInputs]:
    """Write cloud-init + docker-compose.yml + return playbook inputs."""
    dir_ = _instance_dir(instance_id)
    token = secrets.token_urlsafe(32)
    resolved_region = region or "fsn1"  # Falkenstein, EU-central
    server_name = f"nexus-{_short_id(instance_id)}"

    _write_compose(dir_)
    _write_env_placeholders(dir_, token)

    compose_body = (dir_ / "docker-compose.yml").read_text()
    compose_indented = "\n".join(f"      {line}" for line in compose_body.splitlines())

    cloud_init = _CLOUD_INIT_TEMPLATE.format(
        instance_id=instance_id,
        instance_name=instance_name,
        compose_indented=compose_indented,
    )
    (dir_ / "cloud-init.yaml").write_text(cloud_init, encoding="utf-8")

    inputs = PlaybookInputs(
        instance_id=instance_id,
        instance_name=instance_name,
        modality="hetzner",
        region=resolved_region,
        domain=domain,
        deployments_dir=dir_,
        endpoint_hint=domain or f"http://{server_name}.hetzner.local:8000",
        required_secrets=[
            "HCLOUD_TOKEN",
            "PLATFORM_BOOTSTRAP_TOKEN",
            "POSTGRES_PASSWORD",
            "ANTHROPIC_API_KEY",
            "SSH_KEY_NAME",
        ],
        provider_steps=[
            {
                "title": "Export Hetzner Cloud token",
                "cmd": "export HCLOUD_TOKEN=${HCLOUD_TOKEN}",
            },
            {
                "title": "Rewrite the .env in cloud-init with real secrets",
                "cmd": (
                    "envsubst < ./cloud-init.yaml > ./cloud-init.resolved.yaml"
                ),
            },
            {
                "title": "Create the server (cx22 = 2 vCPU / 4 GB RAM / 40 GB, ~€4.15/mo)",
                "cmd": (
                    f"hcloud server create --name {server_name} --image ubuntu-24.04 "
                    f"--type cx22 --location {resolved_region} --ssh-key ${{SSH_KEY_NAME}} "
                    f"--user-data-from-file ./cloud-init.resolved.yaml"
                ),
            },
            {
                "title": "Attach a floating IP (optional but recommended for stable DNS)",
                "cmd": (
                    f"hcloud floating-ip create --type ipv4 --home-location {resolved_region} "
                    f"--name {server_name}-ip && "
                    f"hcloud floating-ip assign {server_name}-ip {server_name}"
                ),
            },
            {
                "title": "Wait for cloud-init to finish and Compose to boot",
                "cmd": (
                    f"hcloud server ssh {server_name} 'cloud-init status --wait && "
                    f"docker compose -f /opt/nexus/docker-compose.yml ps'"
                ),
            },
        ],
        post_deploy_checks=[
            f"hcloud server ssh {server_name} 'curl -fsSL http://localhost:8000/_health'",
            f"hcloud server ssh {server_name} 'curl -fsSL http://localhost:8000/_voice/health'",
        ],
    )
    return dir_, token, inputs


# ────────────────────────────────────────────────────────────────
# Helpers
# ────────────────────────────────────────────────────────────────

def _instance_dir(instance_id: UUID) -> Path:
    d = settings.deployments_dir / str(instance_id)
    d.mkdir(parents=True, exist_ok=True)
    return d


def _short_id(instance_id: UUID) -> str:
    return str(instance_id)[:8]


def _write_compose(dir_: Path) -> None:
    body = _COMPOSE_TEMPLATE.format(
        image=settings.local_platform_image,
        port=8000,
    )
    (dir_ / "docker-compose.yml").write_text(body, encoding="utf-8")


def _write_env_placeholders(dir_: Path, token: str) -> None:
    """Write a `.env.example` — real values live in `nexus.secrets.env`.

    We DO NOT write a real `.env`. That's the whole point of the playbook
    handoff — secrets stay out of Console's disk.
    """
    (dir_ / ".env.example").write_text(
        "# Populate these from nexus.secrets.env before starting Compose.\n"
        f"PLATFORM_BOOTSTRAP_TOKEN={token}  # generated fresh per instance\n"
        "POSTGRES_PASSWORD=change-me\n"
        "ANTHROPIC_API_KEY=change-me\n",
        encoding="utf-8",
    )
