"""Machine-readable spec of the ops catalog. Consumed by generate_ops_cards.py.

Each entry: (id, title, artifact_type, rollout_stage, autonomy, maturity,
role, mode, produces, purpose_line, trigger_or_upstream, side_effect_or_downstream,
tools, tags).

Purpose lines are one sentence, from the operator's perspective.
This is the single source of truth for the 100+ ops cards.
"""
from __future__ import annotations

# Rollout stages
FOUNDATION = "1-foundation"
CAPTURE = "2-capture"
GENERATE = "3-generate"
ORCHESTRATE = "4-orchestrate"

# Autonomy levels
LED = "human-led"
ASSISTED = "human-assisted"
AUTO = "fully-autonomous"

# ---------------------------------------------------------------------
# SALES  — 20 cards
# ---------------------------------------------------------------------
SALES = [
    # Fully autonomous · Foundation
    dict(id="icp_definition", title="ICP Definition", artifact="agent", stage=FOUNDATION, autonomy=AUTO, maturity=1,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="Derives the Ideal Customer Profile from historical wins, product fit signals and market study — firmographics, technographics, buying triggers.",
         reads="Customer records, win/loss notes, product docs", writes="ICP definition markdown + tags for downstream targeting.",
         tools=["read_crm", "web_search", "read_prior_step"],
         tags=["icp", "targeting", "firmographics"]),
    dict(id="market_mapping", title="Market Mapping", artifact="agent", stage=FOUNDATION, autonomy=AUTO, maturity=1,
         role="analyst", mode="single-shot", produces="structured_json",
         purpose="Builds a landscape map of every company matching the ICP in a target geography — segmented by size, sector, funding, tech stack.",
         reads="ICP + geo scope", writes="Structured account list.",
         tools=["web_search", "wide_browse", "fetch_url"],
         tags=["market-map", "landscape", "accounts"]),
    dict(id="database_mining", title="Database Mining", artifact="sidecar", stage=FOUNDATION, autonomy=AUTO, maturity=2,
         role="worker", mode="scheduled", produces="enriched_record",
         purpose="Runs scheduled sweeps against directories (Crunchbase, LinkedIn, industry lists) to keep the target-account database fresh.",
         reads="Source connector list + last sync watermark", writes="New / updated accounts into the CRM staging table.",
         tools=["fetch_url", "wide_browse", "crm_upsert"],
         tags=["mining", "sync", "database"]),
    dict(id="web_maps_scraping", title="Web & Maps Scraping", artifact="sidecar", stage=FOUNDATION, autonomy=AUTO, maturity=2,
         role="worker", mode="scheduled", produces="enriched_record",
         purpose="Pulls prospect signals from public web and geographic sources — Google Maps listings, review sites, industry directories.",
         reads="Vertical + geo scope", writes="Enriched prospect records with geo + business metadata.",
         tools=["fetch_url", "wide_browse", "geocode"],
         tags=["scraping", "maps", "local", "geo"]),
    dict(id="social_mining", title="Social Mining", artifact="sidecar", stage=FOUNDATION, autonomy=AUTO, maturity=2,
         role="worker", mode="scheduled", produces="enriched_record",
         purpose="Watches social platforms (LinkedIn, X, Instagram) for role changes, hiring signals, funding announcements matching the ICP.",
         reads="ICP + platform tokens", writes="Signal events into the trigger stream.",
         tools=["fetch_url", "linkedin_api", "x_api"],
         tags=["social", "signals", "linkedin"]),
    dict(id="list_building", title="List Building", artifact="agent", stage=FOUNDATION, autonomy=AUTO, maturity=2,
         role="integrator", mode="single-shot", produces="structured_json",
         purpose="Consolidates raw accounts from mining + scraping + social into ranked outreach lists per persona and channel.",
         reads="Staged accounts + ICP + persona map", writes="Ranked list per campaign.",
         tools=["read_crm", "score_accounts"],
         tags=["list", "prioritization", "outreach"]),
    dict(id="contact_enrichment", title="Contact Enrichment", artifact="skill", stage=FOUNDATION, autonomy=AUTO, maturity=3,
         role=None, mode=None, produces="enriched_record",
         purpose="Reusable capability: given a name+company, resolve email, phone, LinkedIn, role, tenure, seniority.",
         reads="Contact record with partial fields", writes="Contact record with enriched fields + provenance.",
         tools=["clearbit", "apollo", "hunter"],
         tags=["enrichment", "contact", "skill"]),
    dict(id="email_verification", title="Email Verification", artifact="skill", stage=FOUNDATION, autonomy=AUTO, maturity=4,
         role=None, mode=None, produces="enriched_record",
         purpose="Reusable capability: SMTP+MX+catchall verification with confidence score.",
         reads="Email address", writes="Verification result: valid | risky | invalid + reason.",
         tools=["neverbounce", "zerobounce", "smtp_probe"],
         tags=["email", "verification", "skill", "deliverability"]),
    dict(id="account_enrichment", title="Account Enrichment", artifact="skill", stage=FOUNDATION, autonomy=AUTO, maturity=3,
         role=None, mode=None, produces="enriched_record",
         purpose="Reusable capability: given a domain, resolve firmographics, tech stack, funding, headcount, geo.",
         reads="Domain", writes="Firmographic bundle.",
         tools=["clearbit", "builtwith", "crunchbase"],
         tags=["enrichment", "account", "skill", "firmographics"]),
    dict(id="personalization_research", title="Personalization Research", artifact="agent", stage=FOUNDATION, autonomy=AUTO, maturity=2,
         role="analyst", mode="single-shot", produces="structured_json",
         purpose="For a target contact + account, mines recent posts, blog articles, press mentions and job changes to produce personalization hooks per message.",
         reads="Contact + account records", writes="Personalization brief per contact.",
         tools=["web_search", "fetch_url", "read_crm"],
         tags=["personalization", "research", "hooks"]),

    # Human-assisted · Foundation / Capture
    dict(id="lookalike_modeling", title="Lookalike Modeling", artifact="agent", stage=FOUNDATION, autonomy=ASSISTED, maturity=2,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="Given closed-won accounts, derives statistical lookalike criteria and proposes new target segments for human approval.",
         reads="Closed-won CRM data", writes="Segment proposals with match rationale.",
         tools=["read_crm", "statistical_analysis"],
         tags=["lookalike", "segmentation", "modeling"]),
    dict(id="fit_scoring", title="Fit Scoring", artifact="agent", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role="classifier", mode="single-shot", produces="structured_json",
         purpose="Scores every inbound and mined account against the ICP fit model — 0..100 with dimensional breakdown.",
         reads="Account record + ICP model", writes="Fit score + top 3 gaps + top 3 strengths.",
         tools=["read_crm", "score_accounts"],
         tags=["scoring", "fit", "icp"]),
    dict(id="trigger_detection", title="Trigger Detection", artifact="sidecar", stage=CAPTURE, autonomy=ASSISTED, maturity=2,
         role="classifier", mode="event-driven", produces="side_effect",
         purpose="Detects buying triggers in signal streams (funding, hiring, role change, product launch) and routes them to the right SDR playbook.",
         reads="Signal stream from social/news mining", writes="Trigger events on the sales bus.",
         tools=["subscribe_signals", "classify", "route_to_playbook"],
         tags=["triggers", "signals", "routing"]),

    # Fully autonomous · Generate
    dict(id="cold_email_drafting", title="Cold Email Drafting", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="writer", mode="single-shot", produces="structured_json",
         purpose="Drafts cold-email sequences (3-5 steps) using ICP fit, personalization brief and vertical playbook. Emits subject + body variants.",
         reads="Personalization brief + playbook", writes="Sequence draft with A/B variants.",
         tools=["personalization_hooks", "playbook_reader"],
         tags=["email", "cold", "sequences", "copy"]),
    dict(id="linkedin_messaging", title="LinkedIn Messaging", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="writer", mode="single-shot", produces="structured_json",
         purpose="Drafts LinkedIn connect-notes and follow-up DMs with tone tuned to the prospect's seniority and recent activity.",
         reads="Contact + personalization brief", writes="Multi-step DM sequence.",
         tools=["personalization_hooks", "linkedin_style_guide"],
         tags=["linkedin", "messaging", "dm"]),
    dict(id="cold_call_scripting", title="Cold-Call Scripting", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=2,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Produces a cold-call script skeleton: opener, pain question, value pivot, objection turns, CTA — tuned to persona and vertical.",
         reads="ICP + persona + product one-pager", writes="Call script with branching tree.",
         tools=["playbook_reader", "objection_library_query"],
         tags=["cold-call", "script", "sdr"]),
    dict(id="proof_matching", title="Proof Matching", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=2,
         role="analyst", mode="single-shot", produces="structured_json",
         purpose="Matches a target account to the closest 1-3 case studies, quotes and metrics from the proof library.",
         reads="Account record + proof library", writes="Matched proof set with fit rationale.",
         tools=["read_proof_library", "score_similarity"],
         tags=["proof", "case-study", "social-proof"]),
    dict(id="video_prospecting", title="Video Prospecting", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=1,
         role="writer", mode="single-shot", produces="structured_json",
         purpose="Generates a per-prospect video script and thumbnail brief for tools like Loom/Sendspark — persona-tuned, 45-60 seconds.",
         reads="Personalization brief", writes="Video script + thumbnail brief + suggested CTA.",
         tools=["personalization_hooks"],
         tags=["video", "prospecting", "loom"]),

    # Fully autonomous · Orchestrate
    dict(id="campaign_launch", title="Campaign Launch", artifact="sidecar", stage=GENERATE, autonomy=AUTO, maturity=2,
         role="connector", mode="event-driven", produces="side_effect",
         purpose="Pushes approved sequences into the outbound tool (Outreach, Instantly, Apollo) with the right list, cadence and A/B split.",
         reads="Approved sequence draft + list", writes="Campaign created on outbound platform.",
         tools=["outreach_api", "instantly_api", "apollo_api"],
         tags=["campaign", "launch", "outbound"]),
    dict(id="campaign_orchestration", title="Campaign Orchestration", artifact="agent", stage=ORCHESTRATE, autonomy=AUTO, maturity=2,
         role="coordinator", mode="event-driven", produces="decision",
         purpose="Watches campaign performance, kills bad variants, promotes winners, re-slots contacts across sequences.",
         reads="Sequence performance metrics", writes="Sequence-mutation decisions on the outbound bus.",
         tools=["read_outbound_metrics", "mutate_sequence"],
         tags=["orchestration", "campaign", "bandit"]),
    dict(id="send_optimization", title="Send Optimization", artifact="sidecar", stage=ORCHESTRATE, autonomy=AUTO, maturity=3,
         role="worker", mode="scheduled", produces="side_effect",
         purpose="Optimises send-time per contact using timezone + engagement history and enforces per-inbox rate limits to protect deliverability.",
         reads="Contact activity + inbox reputation", writes="Send-time overrides on the outbound queue.",
         tools=["read_engagement_history", "inbox_reputation"],
         tags=["send-time", "throttle", "deliverability"]),
    dict(id="deliverability", title="Deliverability", artifact="sidecar", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=2,
         role="worker", mode="scheduled", produces="side_effect",
         purpose="Monitors SPF/DKIM/DMARC, warms up inboxes, watches blocklists, alerts on bounce-rate spikes.",
         reads="Inbox list + DNS records", writes="Deliverability status per inbox + alerts.",
         tools=["dns_check", "blocklist_check", "warmup"],
         tags=["deliverability", "email", "spf", "dkim", "dmarc"]),

    # Human-led
    dict(id="offer_positioning", title="Offer & Positioning", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=2,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Founder-led card. Drafts positioning statements, offer packages and pricing tiers for the founder to iterate on.",
         reads="Product docs + market research", writes="Positioning + offers doc.",
         tools=["read_product_docs", "read_prior_step"],
         tags=["positioning", "offer", "founder-led"]),
    dict(id="key_account_relationships", title="Key-Account Relationships", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Founder-led card. Tracks the top strategic accounts, mapped stakeholders, current stage, next best action.",
         reads="CRM strategic tier", writes="Relationship dossier per account.",
         tools=["read_crm", "read_notes"],
         tags=["strategic-accounts", "relationships", "founder-led"]),
    dict(id="brand_voice_final_approvals", title="Brand-Voice & Final Approvals", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=2,
         role="reviewer", mode="single-shot", produces="decision",
         purpose="Founder-led card. Reviews outbound copy against brand voice and approves or rejects with structured feedback.",
         reads="Sequence draft + brand voice guide", writes="Approval decision + inline notes.",
         tools=["brand_voice_guide", "diff"],
         tags=["review", "brand-voice", "founder-led"]),
    dict(id="deal_strategy_big_accounts", title="Deal Strategy on Big Accounts", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="Founder-led card. For each top-10 account, drafts a bespoke pursuit plan: stakeholders, entry point, proof, timeline, risks.",
         reads="Account dossier + key contacts", writes="Pursuit plan per account.",
         tools=["read_crm", "read_notes"],
         tags=["strategy", "big-accounts", "founder-led"]),
]

# ---------------------------------------------------------------------
# DEALS  — 24 cards
# ---------------------------------------------------------------------
DEALS = [
    # Human-led · Ongoing
    dict(id="closing_the_deal", title="Closing the Deal", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="AE-led card. Drafts closing-call briefs, next-steps emails and mutual action plans for the AE to finalise.",
         reads="Deal record + last touches", writes="Closing brief.",
         tools=["read_crm", "read_calls"],
         tags=["closing", "ae-led"]),
    dict(id="discounting_concessions", title="Discounting & Concessions", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="Analyses proposed discount vs deal size, LTV, competitive pressure — recommends approve/counter/hold with rationale.",
         reads="Deal record + pricing floor", writes="Discount recommendation.",
         tools=["read_crm", "pricing_floor"],
         tags=["discount", "concession", "ae-led"]),
    dict(id="strategic_account_calls", title="Strategic Account Calls", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Prepares briefing docs for named-account executive calls — history, open threads, board-level themes, questions to ask.",
         reads="Account dossier", writes="Executive briefing.",
         tools=["read_crm", "read_notes"],
         tags=["strategic-accounts", "ae-led"]),
    dict(id="proposal_final_signoff", title="Proposal Final Sign-Off", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="reviewer", mode="single-shot", produces="decision",
         purpose="Human-led final review of proposals before send — checks pricing, T&C, custom clauses, brand voice.",
         reads="Proposal draft", writes="Approval + inline redlines.",
         tools=["proposal_reader", "diff"],
         tags=["approval", "proposal", "ae-led"]),
    dict(id="win_loss_analysis", title="Win/Loss Analysis", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=2,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="Post-mortem on closed deals — reason codes, sales-cycle length, competitor mentions, product-gap tallies.",
         reads="Closed deals + call transcripts", writes="Win/loss report.",
         tools=["read_crm", "read_calls"],
         tags=["win-loss", "postmortem"]),

    # Human-assisted · Capture / Generate
    dict(id="objection_library", title="Objection Library", artifact="agent", stage=CAPTURE, autonomy=ASSISTED, maturity=2,
         role="analyst", mode="single-shot", produces="structured_json",
         purpose="Mines call transcripts to extract objections, cluster them and produce a searchable library with rebuttal drafts.",
         reads="Call transcripts", writes="Objection clusters + rebuttal drafts.",
         tools=["read_calls", "cluster"],
         tags=["objections", "library", "enablement"]),
    dict(id="objection_response", title="Objection Response", artifact="agent", stage=GENERATE, autonomy=ASSISTED, maturity=2,
         role="writer", mode="single-shot", produces="structured_json",
         purpose="On a live thread, matches the buyer's objection to the library and drafts a response for the AE to send.",
         reads="Thread + objection library", writes="Draft response + confidence score.",
         tools=["objection_library_query", "read_thread"],
         tags=["objection", "response", "ae-assisted"]),
    dict(id="agreement_drafting", title="Agreement Drafting", artifact="agent", stage=GENERATE, autonomy=ASSISTED, maturity=2,
         role="writer", mode="single-shot", produces="structured_json",
         purpose="Drafts contracts from templates with negotiated clauses redlined; flags anything outside pre-approved boundaries.",
         reads="Deal terms + contract template", writes="Redlined draft + risk flags.",
         tools=["contract_templates", "clause_library"],
         tags=["contract", "drafting", "redlines"]),
    dict(id="forecasting", title="Forecasting", artifact="agent", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=3,
         role="analyst", mode="scheduled", produces="markdown_report",
         purpose="Weekly forecast rollup — commit/best-case/pipeline, deal-level probability recalibrated from stage + last-touch signals.",
         reads="Deal + activity data", writes="Forecast with confidence.",
         tools=["read_crm", "read_activity"],
         tags=["forecast", "pipeline"]),

    # Fully autonomous · Capture
    dict(id="reply_classification", title="Reply Classification", artifact="agent", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role="classifier", mode="event-driven", produces="structured_json",
         purpose="Classifies every reply on outbound threads: interested / not-now / OOO / referral / unsubscribe / question / objection.",
         reads="Inbound reply", writes="Classification + routing decision.",
         tools=["read_thread"],
         tags=["reply", "classification"]),
    dict(id="hot_lead_routing", title="Hot-Lead Routing", artifact="sidecar", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role="connector", mode="event-driven", produces="side_effect",
         purpose="Routes hot leads to the right AE based on territory, capacity, ICP fit — SLAs enforced.",
         reads="Classified reply + AE availability", writes="Assignment + calendar invite.",
         tools=["read_crm", "read_availability"],
         tags=["routing", "assignment", "sla"]),
    dict(id="referral_capture", title="Referral Capture", artifact="agent", stage=CAPTURE, autonomy=AUTO, maturity=2,
         role="classifier", mode="event-driven", produces="structured_json",
         purpose="Detects referral offers in replies, extracts referred contact, opens a new record and drafts an intro email.",
         reads="Reply thread", writes="Referred contact + intro draft.",
         tools=["read_thread", "crm_upsert"],
         tags=["referral", "capture"]),
    dict(id="lead_qualification", title="Lead Qualification", artifact="agent", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role="classifier", mode="event-driven", produces="structured_json",
         purpose="Qualifies inbound leads against MEDDPICC/BANT + ICP fit and either books a meeting, nurtures, or disqualifies with reason.",
         reads="Lead record + fit score", writes="Qualification decision.",
         tools=["fit_scoring", "read_crm"],
         tags=["qualification", "meddpicc", "bant"]),
    dict(id="inbox_triage", title="Inbox Triage", artifact="sidecar", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role="classifier", mode="event-driven", produces="side_effect",
         purpose="Deduplicates inbound emails across shared mailboxes, labels by intent, routes to the owning queue.",
         reads="Shared inbox stream", writes="Labels + routing on inbox platform.",
         tools=["gmail_api", "outlook_api"],
         tags=["inbox", "triage", "shared-inbox"]),
    dict(id="call_capture", title="Call Capture", artifact="sidecar", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role="worker", mode="event-driven", produces="side_effect",
         purpose="Records, transcribes and diarises sales calls; pushes structured summaries back to the CRM against the right deal.",
         reads="Meeting bot output", writes="Transcript + summary attached to deal.",
         tools=["gong_api", "fireflies_api", "otter_api"],
         tags=["call", "transcription", "summary"]),
    dict(id="post_call_debrief", title="Post-Call Debrief", artifact="agent", stage=CAPTURE, autonomy=AUTO, maturity=2,
         role="writer", mode="event-driven", produces="markdown_report",
         purpose="From a call transcript, drafts a structured debrief: attendees, decision-makers, pains raised, next steps, blockers.",
         reads="Call transcript", writes="Debrief pushed to deal record.",
         tools=["read_calls"],
         tags=["debrief", "call"]),
    dict(id="crm_hygiene", title="CRM Hygiene", artifact="sidecar", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role="worker", mode="scheduled", produces="side_effect",
         purpose="Detects stale deals, missing fields, orphaned contacts, duplicate accounts — remediates or opens tickets.",
         reads="CRM full scan", writes="Field fills, dedup merges, ticket creates.",
         tools=["read_crm", "crm_upsert", "ticket_create"],
         tags=["crm", "hygiene", "cleanup"]),
    dict(id="pipeline_reporting", title="Pipeline Reporting", artifact="sidecar", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role="worker", mode="scheduled", produces="side_effect",
         purpose="Nightly rollup: pipeline snapshot, stage velocity, coverage, ageing — pushed to dashboards and Slack digest.",
         reads="CRM + activity", writes="Dashboard tables + Slack digest.",
         tools=["read_crm", "post_slack"],
         tags=["pipeline", "reporting", "dashboard"]),

    # Fully autonomous · Generate
    dict(id="meeting_booking", title="Meeting Booking", artifact="sidecar", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="connector", mode="event-driven", produces="side_effect",
         purpose="Handles back-and-forth to book meetings with qualified leads across time zones — proposes slots, holds and confirms.",
         reads="Qualified lead + AE availability", writes="Calendar invite + confirmation email.",
         tools=["chili_piper", "calendly", "google_calendar"],
         tags=["scheduling", "meeting"]),
    dict(id="speed_to_lead", title="Speed-to-Lead", artifact="sidecar", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="worker", mode="event-driven", produces="side_effect",
         purpose="Watches inbound signals and responds within 60 seconds — first-touch email or WhatsApp acknowledging and offering a meeting slot.",
         reads="Fresh inbound signal", writes="First-touch send + meeting-link.",
         tools=["gmail_api", "whatsapp_api", "calendly"],
         tags=["speed", "response-sla", "inbound"]),
    dict(id="comment_cta_fulfillment", title="Comment-CTA Fulfillment", artifact="sidecar", stage=GENERATE, autonomy=AUTO, maturity=2,
         role="worker", mode="event-driven", produces="side_effect",
         purpose="When a prospect drops the CTA keyword on a social post, DMs them the lead magnet and opens a CRM record.",
         reads="Social listening stream", writes="DM + CRM record.",
         tools=["instagram_api", "linkedin_api", "crm_upsert"],
         tags=["cta", "social", "inbound"]),
    dict(id="pre_call_briefing", title="Pre-Call Briefing", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="writer", mode="scheduled", produces="markdown_report",
         purpose="One hour before every call, drafts a briefing: attendee bios, company recap, last touches, likely objections, opening question.",
         reads="Meeting + deal + contacts", writes="Briefing sent to AE.",
         tools=["read_crm", "read_calendar", "web_search"],
         tags=["briefing", "prep"]),
    dict(id="follow_up_drafting", title="Follow-Up Drafting", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="writer", mode="event-driven", produces="structured_json",
         purpose="After every meeting, drafts a follow-up email with the recap, agreed next steps and any attachments — ready to send.",
         reads="Call debrief + deal", writes="Follow-up email draft.",
         tools=["read_calls", "read_crm"],
         tags=["follow-up", "email"]),
    dict(id="demo_prototyping", title="Demo Prototyping", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=1,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Builds a bespoke-demo plan for a target account: which product surfaces to open, data to preload, questions to ask, wow moments.",
         reads="Account brief + product surfaces", writes="Demo plan.",
         tools=["read_crm", "product_surface_index"],
         tags=["demo", "prep"]),
    dict(id="proposal_generation", title="Proposal Generation", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=2,
         role="writer", mode="single-shot", produces="pdf",
         purpose="Assembles a full proposal PDF from a deal record: scope, pricing, timeline, terms, case studies — customised to the buyer.",
         reads="Deal + proof library", writes="Proposal PDF.",
         tools=["proposal_templates", "proof_matching", "write_pdf"],
         tags=["proposal", "pdf"]),
    dict(id="pricing_support", title="Pricing Support", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=2,
         role="analyst", mode="single-shot", produces="structured_json",
         purpose="Answers deal-level pricing questions: recommended tier, packaging, discount if any, guardrails vs pricing floor.",
         reads="Deal + pricing model", writes="Pricing recommendation.",
         tools=["pricing_floor", "read_crm"],
         tags=["pricing", "quote"]),

    # Fully autonomous · Orchestrate
    dict(id="deal_room_assembly", title="Deal Room Assembly", artifact="sidecar", stage=ORCHESTRATE, autonomy=AUTO, maturity=2,
         role="connector", mode="event-driven", produces="side_effect",
         purpose="Provisions a per-deal digital room (DocSend/Notion/Dock) with the right artefacts, tracks buyer engagement, alerts on stalls.",
         reads="Deal record", writes="Room provisioned + engagement stream.",
         tools=["docsend_api", "notion_api", "dock_api"],
         tags=["deal-room", "engagement"]),
    dict(id="reactivation", title="Reactivation", artifact="sidecar", stage=ORCHESTRATE, autonomy=AUTO, maturity=2,
         role="worker", mode="scheduled", produces="side_effect",
         purpose="Watches closed-lost and cold-open deals for reactivation signals — job change, funding, new decision-maker — and reopens with a tailored touch.",
         reads="Closed-lost + cold-open pool", writes="Reactivation touches on the outbound queue.",
         tools=["read_crm", "signal_detection"],
         tags=["reactivation", "closed-lost"]),
]
