"""Second half of the ops catalog spec: marketing, operations, intelligence,
customer, back-office, and vertical-specific cards.

Uses the same tuple shape as ops_catalog_spec.py.
"""
from __future__ import annotations

from scripts.ops_catalog_spec import (
    FOUNDATION, CAPTURE, GENERATE, ORCHESTRATE,
    LED, ASSISTED, AUTO,
)

# ---------------------------------------------------------------------
# MARKETING  — 18 cards
# ---------------------------------------------------------------------
MARKETING = [
    dict(id="brand_voice_guide", title="Brand Voice Guide", artifact="agent", stage=FOUNDATION, autonomy=LED, maturity=2,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Founder-led. Codifies tone, do's/don'ts, vocabulary, examples — the source of truth every content agent reads.",
         reads="Existing content + interviews", writes="Brand voice guide markdown.",
         tools=["read_content", "read_interviews"],
         tags=["brand-voice", "founder-led"]),
    dict(id="content_calendar", title="Content Calendar", artifact="agent", stage=FOUNDATION, autonomy=ASSISTED, maturity=2,
         role="coordinator", mode="single-shot", produces="structured_json",
         purpose="Builds a quarterly calendar with themes, channels, cadence and owners — human approves before it schedules.",
         reads="Marketing goals + brand voice", writes="Calendar tables per channel.",
         tools=["read_brand_voice", "read_prior_step"],
         tags=["calendar", "planning"]),
    dict(id="seo_briefs", title="SEO Briefs", artifact="agent", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="For a target keyword, produces an SEO brief: intent, competitors, outline, headings, entities to cover, target word count.",
         reads="Keyword + SERP", writes="SEO brief.",
         tools=["serp_api", "keyword_tools", "web_search"],
         tags=["seo", "brief", "content"]),
    dict(id="social_posts_generator", title="Social Posts Generator", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="writer", mode="single-shot", produces="structured_json",
         purpose="From a source (post, video, event) drafts platform-specific posts for LinkedIn, X, Instagram, TikTok with hooks and hashtags.",
         reads="Source content + brand voice", writes="Platform posts.",
         tools=["read_brand_voice"],
         tags=["social", "posts", "repurpose"]),
    dict(id="long_form_content_writer", title="Long-Form Content Writer", artifact="agent", stage=GENERATE, autonomy=ASSISTED, maturity=2,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Drafts full blog posts / newsletters from an SEO brief and brand voice — human edits before publish.",
         reads="Brief + brand voice", writes="Article draft.",
         tools=["read_brand_voice"],
         tags=["blog", "long-form", "content"]),
    dict(id="ad_creative_generator", title="Ad Creative Generator", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=2,
         role="writer", mode="single-shot", produces="structured_json",
         purpose="Generates ad-variant sets (headlines, primaries, descriptions) per persona and channel — with A/B split annotations.",
         reads="Persona + product + brand voice", writes="Ad copy variants.",
         tools=["read_brand_voice"],
         tags=["ads", "creative", "copy"]),
    dict(id="landing_page_writer", title="Landing Page Writer", artifact="agent", stage=GENERATE, autonomy=ASSISTED, maturity=2,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Drafts full landing-page copy: hero, sub-hero, sections, social proof placement, CTAs — matched to campaign source.",
         reads="Campaign spec + brand voice + proof library", writes="Landing copy markdown.",
         tools=["read_brand_voice", "proof_matching"],
         tags=["landing-page", "copy"]),
    dict(id="email_nurture_writer", title="Email Nurture Writer", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="writer", mode="single-shot", produces="structured_json",
         purpose="Drafts nurture sequences for each persona / lifecycle stage — welcome, activation, re-engagement.",
         reads="Persona + product + brand voice", writes="Sequence draft.",
         tools=["read_brand_voice"],
         tags=["nurture", "email", "lifecycle"]),
    dict(id="community_moderation", title="Community Moderation", artifact="sidecar", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=2,
         role="classifier", mode="event-driven", produces="side_effect",
         purpose="Watches Discord/Slack/forum channels: flags spam and toxicity, drafts responses on FAQ questions, escalates edge cases.",
         reads="Community message stream", writes="Moderation actions + response drafts.",
         tools=["discord_api", "slack_api"],
         tags=["community", "moderation"]),
    dict(id="pr_press_kit", title="PR & Press Kit", artifact="agent", stage=GENERATE, autonomy=ASSISTED, maturity=1,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Drafts press releases and pitches for news beats — founder announcements, funding, product launches — with journalist targeting.",
         reads="News beat + product docs", writes="Press draft + journalist list.",
         tools=["media_database"],
         tags=["pr", "press", "release"]),
    dict(id="analytics_rollup", title="Marketing Analytics Rollup", artifact="sidecar", stage=ORCHESTRATE, autonomy=AUTO, maturity=3,
         role="worker", mode="scheduled", produces="side_effect",
         purpose="Nightly pull from GA4, ad platforms and CRM into a unified table — sends weekly digest with anomalies flagged.",
         reads="GA4 + ad platforms + CRM", writes="Unified table + weekly digest.",
         tools=["ga4_api", "meta_ads_api", "google_ads_api"],
         tags=["analytics", "rollup", "digest"]),
    dict(id="influencer_outreach", title="Influencer Outreach", artifact="agent", stage=CAPTURE, autonomy=ASSISTED, maturity=2,
         role="analyst", mode="single-shot", produces="structured_json",
         purpose="Finds influencers matching the brand, scores fit, drafts outreach — human approves the shortlist and copy.",
         reads="ICP + brand voice", writes="Ranked influencer list + drafts.",
         tools=["social_search", "engagement_analysis"],
         tags=["influencer", "outreach", "creator"]),
    dict(id="event_planning", title="Event Planning", artifact="agent", stage=GENERATE, autonomy=ASSISTED, maturity=1,
         role="coordinator", mode="single-shot", produces="markdown_report",
         purpose="Plans an event end-to-end: goals, format, target audience, run of show, promo plan, follow-up plan.",
         reads="Event brief", writes="Event plan.",
         tools=["read_brand_voice"],
         tags=["events", "planning"]),
    dict(id="webinar_producer", title="Webinar Producer", artifact="agent", stage=GENERATE, autonomy=ASSISTED, maturity=1,
         role="coordinator", mode="single-shot", produces="markdown_report",
         purpose="Drafts webinar deck outline, invite copy, follow-up sequence and post-event repurposing plan.",
         reads="Topic + audience", writes="Webinar bundle.",
         tools=["read_brand_voice"],
         tags=["webinar", "events"]),
    dict(id="creative_asset_repurpose", title="Creative Asset Repurpose", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=2,
         role="writer", mode="single-shot", produces="structured_json",
         purpose="From one hero asset (long-form video, blog, whitepaper), fans out 10-30 micro-assets across channels.",
         reads="Source asset", writes="Micro-assets bundle.",
         tools=["read_brand_voice"],
         tags=["repurpose", "content", "atomization"]),
    dict(id="paid_ads_optimizer", title="Paid Ads Optimizer", artifact="agent", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=2,
         role="analyst", mode="scheduled", produces="decision",
         purpose="Watches ad performance: identifies losers, proposes bid/creative/audience mutations. Human approves before push.",
         reads="Ad platform performance", writes="Mutation proposals.",
         tools=["meta_ads_api", "google_ads_api"],
         tags=["paid-ads", "optimization"]),
    dict(id="ugc_pipeline", title="UGC Pipeline", artifact="sidecar", stage=CAPTURE, autonomy=AUTO, maturity=2,
         role="worker", mode="event-driven", produces="side_effect",
         purpose="Collects user-generated content mentions, verifies rights, tags for reuse across social and site.",
         reads="Social listening + rights DB", writes="Approved UGC library.",
         tools=["social_listening", "rights_check"],
         tags=["ugc", "content", "social-proof"]),
    dict(id="brief_generation", title="Brief Generation", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=2,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Turns a request into a full creative brief — objective, audience, insight, tone, mandatories, deliverables, deadlines.",
         reads="Request thread + brand voice", writes="Creative brief.",
         tools=["read_brand_voice"],
         tags=["brief", "creative", "agency"]),
]

# ---------------------------------------------------------------------
# OPERATIONS  — 20 cards
# ---------------------------------------------------------------------
OPERATIONS = [
    dict(id="sop_generation", title="SOP Generation", artifact="agent", stage=FOUNDATION, autonomy=LED, maturity=2,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Operator-led. Turns process descriptions and call transcripts into codified SOPs with steps, roles and checklists.",
         reads="Process description + transcripts", writes="SOP doc.",
         tools=["read_calls", "read_notes"],
         tags=["sop", "process", "operator-led"]),
    dict(id="scope_calls", title="Scope Calls", artifact="agent", stage=FOUNDATION, autonomy=LED, maturity=1,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Operator-led. Turns discovery-call transcripts into scoped statements of work.",
         reads="Discovery call transcript", writes="Scope doc.",
         tools=["read_calls"],
         tags=["scope", "sow", "operator-led"]),
    dict(id="client_trust", title="Client Trust", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Operator-led. Drafts trust-building comms: honest updates, escalation letters, apology + remediation letters.",
         reads="Situation notes", writes="Comms drafts.",
         tools=["read_notes"],
         tags=["client-comms", "trust", "operator-led"]),
    dict(id="architecture_decisions", title="Architecture Decisions", artifact="agent", stage=FOUNDATION, autonomy=LED, maturity=1,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="Operator-led. Drafts ADRs: context, decision, alternatives, consequences.",
         reads="Design discussions", writes="ADR doc.",
         tools=["read_notes"],
         tags=["adr", "architecture", "operator-led"]),
    dict(id="final_ship_approval", title="Final Ship Approval", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="reviewer", mode="single-shot", produces="decision",
         purpose="Operator-led. Structured go/no-go review of deliverables before client hand-off.",
         reads="Deliverable + acceptance criteria", writes="Decision + inline notes.",
         tools=["diff"],
         tags=["approval", "gate", "operator-led"]),

    dict(id="access_collection", title="Access Collection", artifact="agent", stage=CAPTURE, autonomy=ASSISTED, maturity=2,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Drafts a per-project access-collection checklist and follow-up messages until every credential lands in the vault.",
         reads="Project stack", writes="Access checklist + reminder drafts.",
         tools=["read_stack", "vault_status"],
         tags=["access", "credentials", "onboarding"]),
    dict(id="data_migration", title="Data Migration", artifact="sidecar", stage=CAPTURE, autonomy=ASSISTED, maturity=2,
         role="worker", mode="event-driven", produces="side_effect",
         purpose="Orchestrates data-migration jobs between source and destination systems; produces mapping doc, diff report, rollback plan.",
         reads="Source + target schemas", writes="Migration report.",
         tools=["schema_diff", "etl_runner"],
         tags=["migration", "etl"]),
    dict(id="handoff_docs", title="Handoff Docs", artifact="agent", stage=GENERATE, autonomy=ASSISTED, maturity=2,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="From project artefacts, drafts client-facing handoff docs: overview, decisions, ops runbook, contact list, next steps.",
         reads="Project workspace", writes="Handoff doc.",
         tools=["read_workspace"],
         tags=["handoff", "documentation"]),
    dict(id="qa_verification", title="QA & Verification", artifact="agent", stage=CAPTURE, autonomy=ASSISTED, maturity=2,
         role="reviewer", mode="single-shot", produces="markdown_report",
         purpose="Runs acceptance-criteria checks against deliverables and flags gaps for the operator to fix.",
         reads="Deliverable + acceptance criteria", writes="QA report.",
         tools=["diff", "policy_check"],
         tags=["qa", "verification"]),
    dict(id="agent_evaluation", title="Agent Evaluation", artifact="agent", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=2,
         role="judge", mode="single-shot", produces="structured_json",
         purpose="Runs eval suites against production agents — regression, adversarial, cost. Emits scorecards and gates promotion.",
         reads="Agent + eval suites", writes="Scorecard + promotion gate.",
         tools=["eval_runner"],
         tags=["evals", "quality-gate"]),
    dict(id="monitoring_alerting", title="Monitoring & Alerting", artifact="sidecar", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=3,
         role="worker", mode="scheduled", produces="side_effect",
         purpose="Watches agents in production: latency, error rate, cost, output shape. Fires alerts on anomalies.",
         reads="Agent metrics stream", writes="Alerts on ops channel.",
         tools=["metrics_api", "post_slack"],
         tags=["monitoring", "alerting", "sre"]),
    dict(id="incident_response", title="Incident Response", artifact="agent", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=2,
         role="coordinator", mode="event-driven", produces="markdown_report",
         purpose="Coordinates incident playbook: opens war-room, drafts status updates, tracks timeline, writes postmortem.",
         reads="Alert + timeline", writes="Incident report + postmortem.",
         tools=["war_room", "post_slack", "read_metrics"],
         tags=["incident", "postmortem"]),

    dict(id="project_scaffolding", title="Project Scaffolding", artifact="sidecar", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="connector", mode="event-driven", produces="side_effect",
         purpose="On project kickoff, provisions the workspace: repo, folder tree, base docs, chat channel, project management board.",
         reads="Project template + client info", writes="Provisioned workspace.",
         tools=["github_api", "notion_api", "slack_api"],
         tags=["scaffolding", "kickoff", "provisioning"]),
    dict(id="integration_builds", title="Integration Builds", artifact="agent", stage=GENERATE, autonomy=ASSISTED, maturity=2,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Drafts integration specs against third-party APIs — auth, endpoints, quotas, error paths, test plan.",
         reads="API docs + use case", writes="Integration spec.",
         tools=["fetch_url", "read_api_docs"],
         tags=["integration", "api", "spec"]),
    dict(id="transcript_processing", title="Transcript Processing", artifact="sidecar", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role="worker", mode="event-driven", produces="side_effect",
         purpose="Watches meeting-recorder outputs, cleans transcripts, extracts action items, publishes to the right channel.",
         reads="Meeting recorder stream", writes="Cleaned transcript + action items.",
         tools=["fireflies_api", "notion_api"],
         tags=["transcript", "meetings"]),
    dict(id="context_maintenance", title="Context Maintenance", artifact="sidecar", stage=CAPTURE, autonomy=AUTO, maturity=2,
         role="worker", mode="scheduled", produces="side_effect",
         purpose="Keeps the company brain fresh: refreshes indexed docs, dedups, expires stale entries, rebuilds embeddings.",
         reads="Doc corpus + last-refresh watermarks", writes="Refreshed index.",
         tools=["vector_db", "embed_api"],
         tags=["context", "brain", "index"]),
    dict(id="document_extraction", title="Document Extraction", artifact="skill", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role=None, mode=None, produces="structured_json",
         purpose="Reusable capability: from a document (PDF, DOCX, PPTX), extracts structured fields defined by a schema.",
         reads="Document + schema", writes="Structured record.",
         tools=["read_pdf", "read_docx", "extract_fields"],
         tags=["extraction", "documents", "skill"]),
    dict(id="cost_usage_tracking", title="Cost & Usage Tracking", artifact="sidecar", stage=ORCHESTRATE, autonomy=AUTO, maturity=3,
         role="worker", mode="scheduled", produces="side_effect",
         purpose="Aggregates per-agent, per-tenant token + tool costs; alerts on budget overruns and pushes weekly cost digest.",
         reads="Provider usage APIs + tool ledger", writes="Cost table + digest.",
         tools=["provider_usage_api", "post_slack"],
         tags=["cost", "usage", "finops"]),
    dict(id="meeting_follow_ups", title="Meeting Follow-Ups", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="writer", mode="event-driven", produces="structured_json",
         purpose="After every meeting, drafts recap + action items + follow-up email — one bundle per attendee group.",
         reads="Meeting transcript + calendar", writes="Follow-up bundle.",
         tools=["read_calls", "read_calendar"],
         tags=["follow-up", "meetings"]),
    dict(id="portal_sync", title="Portal Sync", artifact="sidecar", stage=ORCHESTRATE, autonomy=AUTO, maturity=2,
         role="connector", mode="scheduled", produces="side_effect",
         purpose="Two-way sync between the client portal and internal systems (CRM, PM tool) so state is never stale.",
         reads="Portal + internal system", writes="Reconciled state on both sides.",
         tools=["portal_api", "crm_api", "pm_api"],
         tags=["sync", "portal"]),
    dict(id="kickoff_pack", title="Kickoff Pack", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=2,
         role="writer", mode="single-shot", produces="pdf",
         purpose="Assembles the client kickoff pack: goals, roles, timeline, comms cadence, escalation path, artefacts.",
         reads="Project brief", writes="Kickoff pack PDF.",
         tools=["proposal_templates", "write_pdf"],
         tags=["kickoff", "onboarding"]),
    dict(id="status_updates", title="Status Updates", artifact="agent", stage=ORCHESTRATE, autonomy=AUTO, maturity=3,
         role="writer", mode="scheduled", produces="markdown_report",
         purpose="Weekly rollup for each active project: what shipped, what's next, what's blocked. Auto-sent unless flagged.",
         reads="Project workspace + PM board", writes="Weekly status.",
         tools=["read_pm_board", "read_workspace"],
         tags=["status", "weekly-update"]),
]

# ---------------------------------------------------------------------
# INTELLIGENCE  — 17 cards
# ---------------------------------------------------------------------
INTELLIGENCE = [
    dict(id="research_prioritization", title="What to Research Next", artifact="agent", stage=FOUNDATION, autonomy=LED, maturity=1,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="Analyst-led. Given open questions, ranks the next 3-5 research targets by decision value and cost to answer.",
         reads="Question queue", writes="Ranked research plan.",
         tools=["read_notes"],
         tags=["research-plan", "analyst-led"]),
    dict(id="reading_between_lines", title="Reading Between the Lines", artifact="agent", stage=CAPTURE, autonomy=LED, maturity=1,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="Analyst-led. Interprets ambiguous signals (org changes, hiring, PR silence) into a working hypothesis about the target.",
         reads="Public signals", writes="Interpretation memo.",
         tools=["web_search", "read_signals"],
         tags=["signals", "interpretation", "analyst-led"]),
    dict(id="warm_intro_pathing", title="Warm Intro", artifact="agent", stage=CAPTURE, autonomy=LED, maturity=1,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="Analyst-led. From LinkedIn graph and address book, drafts the best warm-intro path to a target contact.",
         reads="Address book + LinkedIn", writes="Intro path + ask draft.",
         tools=["linkedin_api", "address_book"],
         tags=["warm-intro", "network"]),
    dict(id="trusting_the_call", title="Trusting the Call", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="judge", mode="single-shot", produces="decision",
         purpose="Analyst-led. Reviews an outsized recommendation, checks reasoning against base rates and known biases, calls the shot.",
         reads="Recommendation + supporting evidence", writes="Go/hold/re-run decision.",
         tools=["read_prior_step"],
         tags=["decision", "judgement", "analyst-led"]),
    dict(id="network_mapping", title="Network Mapping", artifact="agent", stage=FOUNDATION, autonomy=LED, maturity=1,
         role="analyst", mode="single-shot", produces="structured_json",
         purpose="Analyst-led. Maps stakeholder networks around a target account or ecosystem: nodes, edges, influence flow.",
         reads="LinkedIn + press + CRM", writes="Network graph.",
         tools=["linkedin_api", "web_search"],
         tags=["network", "graph", "stakeholders"]),

    dict(id="buying_committee_mapping", title="Buying-Committee Mapping", artifact="agent", stage=CAPTURE, autonomy=ASSISTED, maturity=2,
         role="analyst", mode="single-shot", produces="structured_json",
         purpose="For a target account, maps the buying committee: economic buyer, champion, users, blockers — with stances and gaps.",
         reads="Account + LinkedIn + call transcripts", writes="Committee map + gaps.",
         tools=["linkedin_api", "read_calls"],
         tags=["committee", "meddpicc"]),
    dict(id="warm_path_finding", title="Warm-Path Finding", artifact="sidecar", stage=CAPTURE, autonomy=ASSISTED, maturity=2,
         role="worker", mode="event-driven", produces="structured_json",
         purpose="Continuously scans your network for warm paths into target accounts as new connections and job changes appear.",
         reads="Target list + LinkedIn graph", writes="Warm-path suggestions.",
         tools=["linkedin_api"],
         tags=["warm-path", "network"]),
    dict(id="account_monitoring", title="Account Monitoring", artifact="sidecar", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=3,
         role="worker", mode="scheduled", produces="side_effect",
         purpose="Watches target accounts for news, filings, hiring, executive moves — surfaces trigger events to the SDR/AE.",
         reads="Account list", writes="Trigger events.",
         tools=["web_search", "news_api", "linkedin_api"],
         tags=["monitoring", "signals", "accounts"]),
    dict(id="news_mention_tracking", title="News & Mention Tracking", artifact="sidecar", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=3,
         role="worker", mode="scheduled", produces="side_effect",
         purpose="Watches media for mentions of company, competitors, partners; routes noteworthy items to owners.",
         reads="Watchlist", writes="Digest per owner.",
         tools=["news_api", "google_alerts"],
         tags=["news", "monitoring", "brand"]),

    dict(id="company_deep_dive", title="Company Deep-Dive", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="Produces a company deep-dive: history, funding, product, GTM, tech stack, org, financials, competitive position.",
         reads="Company name", writes="Deep-dive report.",
         tools=["web_search", "crunchbase", "similarweb"],
         tags=["research", "deep-dive"]),
    dict(id="tech_stack_detection", title="Tech-Stack Detection", artifact="skill", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role=None, mode=None, produces="structured_json",
         purpose="Reusable capability: detects a company's tech stack from web pages, job postings and public repos.",
         reads="Company domain + jobs pages", writes="Detected stack.",
         tools=["builtwith", "wappalyzer", "read_jobs"],
         tags=["tech-stack", "skill"]),
    dict(id="funding_financials_lookup", title="Funding & Financials Lookup", artifact="skill", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role=None, mode=None, produces="structured_json",
         purpose="Reusable capability: resolves funding rounds, investors, filings, headcount ranges from public sources.",
         reads="Company name", writes="Structured funding record.",
         tools=["crunchbase", "sec_edgar", "linkedin_api"],
         tags=["funding", "financials", "skill"]),
    dict(id="person_research", title="Person Research", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="For a target person, builds a dossier: role history, education, public writing, talks, network overlap.",
         reads="Person + LinkedIn + web", writes="Person dossier.",
         tools=["linkedin_api", "web_search"],
         tags=["person", "dossier", "research"]),
    dict(id="pricing_research", title="Pricing Research", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=2,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="Reconstructs a competitor's pricing from public pages + procurement leaks + community reports.",
         reads="Competitor list", writes="Pricing teardown.",
         tools=["web_search", "fetch_url"],
         tags=["pricing", "competitive"]),
    dict(id="tam_market_sizing", title="TAM / Market Sizing", artifact="agent", stage=GENERATE, autonomy=ASSISTED, maturity=2,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="Bottom-up and top-down market sizing with declared assumptions and sensitivity ranges.",
         reads="Market brief", writes="TAM/SAM/SOM memo.",
         tools=["web_search", "statistical_analysis"],
         tags=["tam", "market-sizing"]),
    dict(id="competitor_teardown", title="Competitor Teardown", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="Structured competitor teardown: offering, pricing, positioning, moats, weaknesses, threat level.",
         reads="Competitor list", writes="Teardown report.",
         tools=["web_search", "fetch_url"],
         tags=["competitor", "teardown"]),
    dict(id="vertical_analysis", title="Vertical Analysis", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=2,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="Deep dive on a vertical: value chain, key players, unit economics, tech maturity, regulatory landscape.",
         reads="Vertical name", writes="Vertical brief.",
         tools=["web_search", "read_reports"],
         tags=["vertical", "sector"]),
    dict(id="alert_routing", title="Alert Routing", artifact="sidecar", stage=ORCHESTRATE, autonomy=AUTO, maturity=3,
         role="connector", mode="event-driven", produces="side_effect",
         purpose="Routes intelligence alerts to the right owner + channel by topic, account and priority — dedups and rate-limits.",
         reads="Alert stream", writes="Owner-routed alerts.",
         tools=["post_slack", "email"],
         tags=["alerts", "routing"]),
    dict(id="research_reports", title="Research Reports", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="writer", mode="single-shot", produces="pdf",
         purpose="Full research-report assembly: cover, exec summary, sections, charts, appendix. PDF output for stakeholders.",
         reads="Research corpus", writes="Report PDF.",
         tools=["write_pdf", "chart_render"],
         tags=["report", "pdf"]),
    dict(id="data_visualization", title="Data Visualization", artifact="skill", stage=GENERATE, autonomy=AUTO, maturity=3,
         role=None, mode=None, produces="structured_json",
         purpose="Reusable capability: renders charts (bar, line, sankey, choropleth) from a structured dataset spec.",
         reads="Dataset + spec", writes="Chart image or embed.",
         tools=["chart_render"],
         tags=["viz", "chart", "skill"]),
    dict(id="adversarial_verification", title="Adversarial Verification", artifact="agent", stage=ORCHESTRATE, autonomy=AUTO, maturity=2,
         role="judge", mode="debate", produces="decision",
         purpose="Runs an adversarial verifier over research outputs — checks citations, logic, counter-evidence — before shipping.",
         reads="Report draft", writes="Verification verdict + edit list.",
         tools=["citation_check", "counter_search"],
         tags=["verification", "adversarial", "quality"]),
]

# ---------------------------------------------------------------------
# CUSTOMER  — 14 cards
# ---------------------------------------------------------------------
CUSTOMER = [
    dict(id="renewal_negotiation", title="Renewal Negotiation", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="CSM-led. Drafts renewal position and negotiation brief for the CSM to run the conversation.",
         reads="Account health + usage", writes="Renewal brief.",
         tools=["read_crm", "read_usage"],
         tags=["renewal", "csm-led"]),
    dict(id="expansion_playbook", title="Renewals & Expansion", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="CSM-led. Detects expansion openings from usage + roadmap fit and drafts a proposal + plan.",
         reads="Usage + roadmap + account", writes="Expansion plan.",
         tools=["read_usage", "read_roadmap"],
         tags=["expansion", "upsell", "csm-led"]),
    dict(id="strategic_customer_accounts", title="Strategic Customer Accounts", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="CSM-led. Ongoing dossier for the top-10 customer accounts: goals, health, roadmap fit, exec relationships.",
         reads="Customer records", writes="Dossier per account.",
         tools=["read_crm", "read_notes"],
         tags=["strategic-accounts", "csm-led"]),
    dict(id="save_calls", title="Save Calls", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="CSM-led. Prepares churn-save call brief: reason for churn, options, concessions, walk-away line.",
         reads="Account + churn signal", writes="Save-call brief.",
         tools=["read_crm", "read_usage"],
         tags=["save", "churn", "csm-led"]),

    dict(id="ticket_triage", title="Ticket Triage", artifact="agent", stage=CAPTURE, autonomy=ASSISTED, maturity=3,
         role="classifier", mode="event-driven", produces="structured_json",
         purpose="Classifies inbound tickets: intent, urgency, product area, sentiment, PII. Suggests owner and SLA.",
         reads="Ticket text + customer", writes="Classification + routing suggestion.",
         tools=["helpdesk_api"],
         tags=["ticket", "triage", "cx"]),
    dict(id="escalations", title="Escalations", artifact="agent", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=2,
         role="coordinator", mode="event-driven", produces="markdown_report",
         purpose="Detects escalation-worthy tickets and drafts an escalation packet + comms to internal owners and customer.",
         reads="Ticket history + account", writes="Escalation packet.",
         tools=["helpdesk_api", "read_crm"],
         tags=["escalation", "cx"]),
    dict(id="health_scoring", title="Health Scoring", artifact="sidecar", stage=CAPTURE, autonomy=ASSISTED, maturity=3,
         role="classifier", mode="scheduled", produces="structured_json",
         purpose="Rolls usage, sentiment, tickets and NPS into a per-customer health score with drivers and recommended play.",
         reads="Usage + tickets + surveys", writes="Health scores.",
         tools=["read_usage", "helpdesk_api"],
         tags=["health", "csm", "signals"]),
    dict(id="community_moderation_cx", title="Community Moderation", artifact="sidecar", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=2,
         role="classifier", mode="event-driven", produces="side_effect",
         purpose="Watches customer communities; flags issues, drafts responses, escalates edge cases to CX humans.",
         reads="Community stream", writes="Moderation actions + drafts.",
         tools=["discord_api", "slack_api"],
         tags=["community", "moderation", "cx"]),
    dict(id="advocacy_referrals", title="Advocacy & Referrals", artifact="agent", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=2,
         role="analyst", mode="scheduled", produces="structured_json",
         purpose="Identifies advocacy candidates (high NPS + open reviewer + case-study fit) and drafts an ask.",
         reads="NPS + usage + reviews", writes="Advocacy queue + ask drafts.",
         tools=["read_nps", "read_reviews"],
         tags=["advocacy", "referral"]),
    dict(id="churn_prediction", title="Churn Prediction", artifact="sidecar", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=2,
         role="classifier", mode="scheduled", produces="structured_json",
         purpose="Predicts churn risk 90 days out using usage, tickets, comms signals; explains top drivers per account.",
         reads="Health signals", writes="Churn risk table.",
         tools=["read_usage", "helpdesk_api"],
         tags=["churn", "prediction"]),

    dict(id="faq_self_serve", title="FAQ & Self-Serve", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="writer", mode="event-driven", produces="markdown_report",
         purpose="From tickets and docs, auto-drafts FAQ entries and self-serve articles for repeat questions.",
         reads="Ticket corpus + docs", writes="Draft KB article.",
         tools=["helpdesk_api", "docs_search"],
         tags=["kb", "self-serve"]),
    dict(id="macro_authoring", title="Macro Authoring", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="writer", mode="single-shot", produces="structured_json",
         purpose="Builds and maintains helpdesk macros from repeat replies — tone-tuned to the brand.",
         reads="Reply corpus", writes="Macro set.",
         tools=["helpdesk_api", "read_brand_voice"],
         tags=["macro", "helpdesk"]),
    dict(id="qbr_prep", title="QBR Prep", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=2,
         role="writer", mode="single-shot", produces="pptx",
         purpose="Prepares the QBR deck: usage trends, wins, risks, roadmap ask, exec asks.",
         reads="Customer usage + notes + roadmap", writes="QBR deck.",
         tools=["read_usage", "write_pptx"],
         tags=["qbr", "csm"]),
    dict(id="engagement_replies", title="Engagement & Replies", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="writer", mode="event-driven", produces="structured_json",
         purpose="Drafts personal replies to tickets — brand-voice tuned, cited from docs, human clicks send.",
         reads="Ticket thread + docs", writes="Reply draft.",
         tools=["helpdesk_api", "docs_search", "read_brand_voice"],
         tags=["reply", "helpdesk"]),
    dict(id="onboarding_journeys", title="Onboarding Journeys", artifact="sidecar", stage=ORCHESTRATE, autonomy=AUTO, maturity=2,
         role="worker", mode="event-driven", produces="side_effect",
         purpose="Runs personalised onboarding: sequences, in-app nudges, milestone check-ins based on plan + persona.",
         reads="Onboarding events", writes="Sequences + in-app nudges.",
         tools=["email", "in_app_messaging"],
         tags=["onboarding", "lifecycle"]),
    dict(id="event_coordination", title="Event Coordination", artifact="agent", stage=GENERATE, autonomy=ASSISTED, maturity=2,
         role="coordinator", mode="single-shot", produces="markdown_report",
         purpose="Coordinates customer events end-to-end — invites, agenda, RSVPs, dinner reservations, follow-ups.",
         reads="Event brief + guest list", writes="Coordination plan + comms.",
         tools=["calendar_api", "email"],
         tags=["events", "customer"]),
]

# ---------------------------------------------------------------------
# BACK OFFICE  — 18 cards
# ---------------------------------------------------------------------
BACK_OFFICE = [
    dict(id="hiring_decisions", title="Hiring Decisions", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Founder-led. Structures hiring debriefs and drafts offer packages with rationale.",
         reads="Interview scorecards", writes="Hiring memo.",
         tools=["read_notes"],
         tags=["hiring", "founder-led"]),
    dict(id="compliance_signoff", title="Compliance Sign-Off", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="reviewer", mode="single-shot", produces="decision",
         purpose="Founder-led. Structured compliance sign-off on releases, contracts, campaigns.",
         reads="Item + policy pack", writes="Sign-off decision.",
         tools=["policy_check"],
         tags=["compliance", "founder-led"]),
    dict(id="banking_operations", title="Banking", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Founder-led. Drafts wires, account setups, treasury moves for the founder to authorise.",
         reads="Cash position + payables", writes="Banking instructions.",
         tools=["banking_api", "read_ledger"],
         tags=["banking", "treasury", "founder-led"]),
    dict(id="spend_authority", title="Spend Authority", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="reviewer", mode="single-shot", produces="decision",
         purpose="Founder-led. Approves or holds spend requests against policy + budget.",
         reads="Spend request + budget", writes="Decision.",
         tools=["read_budget", "policy_check"],
         tags=["spend", "approval", "founder-led"]),
    dict(id="entity_compliance", title="Entity Compliance", artifact="agent", stage=CAPTURE, autonomy=LED, maturity=1,
         role="analyst", mode="scheduled", produces="markdown_report",
         purpose="Founder-led. Tracks annual filings, board resolutions, corporate books across entities (US, ES, EE).",
         reads="Entity registry + calendars", writes="Compliance state + next actions.",
         tools=["read_registry"],
         tags=["entity", "compliance", "founder-led"]),
    dict(id="candidate_sourcing", title="Candidate Sourcing", artifact="agent", stage=CAPTURE, autonomy=LED, maturity=1,
         role="analyst", mode="single-shot", produces="structured_json",
         purpose="Founder-led. Sources candidate shortlists from LinkedIn + referrals + niche communities against a role scorecard.",
         reads="Role scorecard", writes="Ranked candidate list.",
         tools=["linkedin_api", "read_references"],
         tags=["hiring", "sourcing", "founder-led"]),

    dict(id="expense_categorization", title="Expense Categorization", artifact="sidecar", stage=CAPTURE, autonomy=ASSISTED, maturity=3,
         role="classifier", mode="scheduled", produces="side_effect",
         purpose="Classifies bank + card transactions into chart of accounts; flags unknowns for human review.",
         reads="Transactions", writes="Categorised ledger.",
         tools=["banking_api", "read_ledger"],
         tags=["expense", "accounting"]),
    dict(id="contract_lifecycle", title="Contract Lifecycle", artifact="sidecar", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=2,
         role="worker", mode="event-driven", produces="side_effect",
         purpose="Tracks contract states across systems (sent, signed, active, renewal, terminated); alerts on lapses and renewals.",
         reads="Contract records", writes="State transitions + alerts.",
         tools=["docusign_api", "notion_api"],
         tags=["contract", "lifecycle"]),
    dict(id="screening_scheduling", title="Screening & Scheduling", artifact="sidecar", stage=CAPTURE, autonomy=ASSISTED, maturity=2,
         role="connector", mode="event-driven", produces="side_effect",
         purpose="Runs first-round screens (short-answer questionnaires) and books interviews across the panel.",
         reads="Candidate pipeline", writes="Screen results + calendar invites.",
         tools=["email", "calendar_api"],
         tags=["hiring", "screening"]),
    dict(id="hr_policy_assistant", title="HR & Policy Assistant", artifact="agent", stage=GENERATE, autonomy=ASSISTED, maturity=2,
         role="writer", mode="event-driven", produces="markdown_report",
         purpose="Answers employee questions against policy pack, generates offer letters, PIPs and separation letters (draft only).",
         reads="Policy pack + request", writes="Response or draft doc.",
         tools=["policy_pack", "letter_templates"],
         tags=["hr", "policy"]),
    dict(id="collections", title="Collections", artifact="agent", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=2,
         role="writer", mode="scheduled", produces="markdown_report",
         purpose="Runs the collections cadence: identifies overdue invoices, drafts escalating comms, escalates to human on impasse.",
         reads="AR ledger", writes="Cadence drafts.",
         tools=["read_ledger", "email"],
         tags=["collections", "ar"]),
    dict(id="cash_flow_forecasting", title="Cash-Flow Forecasting", artifact="agent", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=2,
         role="analyst", mode="scheduled", produces="markdown_report",
         purpose="Weekly 13-week cash-flow forecast with scenarios, drivers, alerts on runway shrinkage.",
         reads="Ledger + AR + AP + payroll", writes="Forecast + scenarios.",
         tools=["read_ledger", "statistical_analysis"],
         tags=["cash-flow", "forecast"]),

    dict(id="document_filing", title="Document Filing", artifact="sidecar", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role="worker", mode="event-driven", produces="side_effect",
         purpose="Auto-files inbound documents (invoices, contracts, receipts) into the right vault folders with metadata.",
         reads="Document intake queue", writes="Filed docs + metadata.",
         tools=["read_pdf", "vault_api"],
         tags=["filing", "documents"]),
    dict(id="payment_tracking", title="Payment Tracking", artifact="sidecar", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role="worker", mode="scheduled", produces="side_effect",
         purpose="Reconciles bank + processor + invoice states; flags mismatches for AR/AP.",
         reads="Bank + processor + AR ledger", writes="Reconciliation report + tickets.",
         tools=["banking_api", "stripe_api", "read_ledger"],
         tags=["payments", "reconciliation"]),
    dict(id="invoice_generation", title="Invoice Generation", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="writer", mode="event-driven", produces="pdf",
         purpose="Generates invoices from CRM/PM events, delivers to the customer portal + email, syncs to ledger.",
         reads="Deal + milestone events", writes="Invoice PDFs + ledger entries.",
         tools=["read_crm", "read_pm_board", "write_pdf"],
         tags=["invoice", "billing"]),
    dict(id="goal_pacing", title="Goal Pacing", artifact="sidecar", stage=ORCHESTRATE, autonomy=AUTO, maturity=2,
         role="worker", mode="scheduled", produces="side_effect",
         purpose="Rolls up KPI attainment vs plan; sends weekly pacing digest with lagging metrics highlighted.",
         reads="KPI streams", writes="Pacing digest.",
         tools=["read_kpis", "post_slack"],
         tags=["pacing", "kpi"]),
    dict(id="revenue_reporting", title="Revenue Reporting", artifact="sidecar", stage=ORCHESTRATE, autonomy=AUTO, maturity=3,
         role="worker", mode="scheduled", produces="side_effect",
         purpose="Monthly revenue rollup by product, segment, geo; sends board pack pre-draft.",
         reads="Billing + CRM", writes="Board pack draft.",
         tools=["read_billing", "read_crm", "write_pptx"],
         tags=["revenue", "reporting", "board"]),
    dict(id="onboarding_training", title="Onboarding & Training", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=2,
         role="writer", mode="event-driven", produces="markdown_report",
         purpose="Personalises new-hire onboarding and training plans by role and function; tracks completion.",
         reads="Role + team", writes="Onboarding plan + checklists.",
         tools=["policy_pack", "read_role_scorecard"],
         tags=["onboarding", "hr", "training"]),
    dict(id="calendar_management", title="Calendar Management", artifact="sidecar", stage=ORCHESTRATE, autonomy=AUTO, maturity=3,
         role="worker", mode="event-driven", produces="side_effect",
         purpose="Manages exec calendars: batches meetings, protects deep-work blocks, reschedules conflicts.",
         reads="Calendar + priorities", writes="Reshuffles + confirmations.",
         tools=["calendar_api"],
         tags=["calendar", "eaa"]),
    dict(id="budget_tracking", title="Budget Tracking", artifact="sidecar", stage=ORCHESTRATE, autonomy=AUTO, maturity=3,
         role="worker", mode="scheduled", produces="side_effect",
         purpose="Tracks budget vs actuals per department + project; sends monthly burn digest with variance notes.",
         reads="Budget + actuals", writes="Burn digest.",
         tools=["read_ledger", "read_budget"],
         tags=["budget", "burn"]),
    dict(id="crm_sync", title="CRM Sync", artifact="sidecar", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role="connector", mode="scheduled", produces="side_effect",
         purpose="Two-way sync between primary CRM and secondary systems (billing, PM, marketing) with idempotent upserts.",
         reads="System-of-record deltas", writes="Reconciled state.",
         tools=["crm_api", "billing_api", "pm_api"],
         tags=["sync", "crm", "connector"]),
    dict(id="email_triage_office", title="Email Triage", artifact="sidecar", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role="classifier", mode="event-driven", produces="side_effect",
         purpose="Classifies exec inbox: urgent / needs-reply / FYI / newsletter / spam; drafts responses on repeatable buckets.",
         reads="Exec inbox stream", writes="Labels + draft responses.",
         tools=["gmail_api", "outlook_api"],
         tags=["inbox", "exec", "triage"]),
]

# ---------------------------------------------------------------------
# VERTICALS  — real-estate, marketing-agency, nightclub
# ---------------------------------------------------------------------
REAL_ESTATE = [
    dict(id="property_dossier", title="Property Dossier", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=2,
         role="analyst", mode="single-shot", produces="pdf",
         purpose="Compiles per-property dossier: title chain, comparables, rental yield, condition report, neighbourhood brief.",
         reads="Address + registry + comparables", writes="Property dossier PDF.",
         tools=["cadastre_api", "comparables_api", "write_pdf"],
         tags=["property", "dossier", "real-estate"],
         vertical="real-estate"),
    dict(id="listing_generator", title="Listing Generator", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=3,
         role="writer", mode="single-shot", produces="structured_json",
         purpose="Writes listing copy + selects hero images + generates floor-plan captions across portals (Idealista, Fotocasa, Zillow).",
         reads="Property record + photos", writes="Portal-ready listings.",
         tools=["read_property", "portal_apis"],
         tags=["listing", "portals", "real-estate"],
         vertical="real-estate"),
    dict(id="buyer_matching", title="Buyer Matching", artifact="agent", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role="classifier", mode="scheduled", produces="structured_json",
         purpose="Matches new listings to buyer search briefs — surfaces top matches to agents.",
         reads="Listings + buyer briefs", writes="Match set per buyer.",
         tools=["read_crm", "score_similarity"],
         tags=["matching", "buyers", "real-estate"],
         vertical="real-estate"),
    dict(id="open_house_coordination", title="Open House Coordination", artifact="sidecar", stage=GENERATE, autonomy=ASSISTED, maturity=2,
         role="connector", mode="event-driven", produces="side_effect",
         purpose="Plans open houses: slots, invites, agent staffing, follow-up sequences to attendees.",
         reads="Property + agent availability", writes="Schedule + sequences.",
         tools=["calendar_api", "email", "whatsapp_api"],
         tags=["open-house", "real-estate"],
         vertical="real-estate"),
    dict(id="offer_letter_drafting", title="Offer Letter Drafting", artifact="agent", stage=GENERATE, autonomy=ASSISTED, maturity=2,
         role="writer", mode="single-shot", produces="pdf",
         purpose="Drafts offer letters and counter-offers with contingencies pre-populated from state templates.",
         reads="Offer terms + property", writes="Offer letter PDF.",
         tools=["contract_templates", "write_pdf"],
         tags=["offer", "contract", "real-estate"],
         vertical="real-estate"),
    dict(id="closing_coordination", title="Closing Coordination", artifact="agent", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=1,
         role="coordinator", mode="single-shot", produces="markdown_report",
         purpose="Coordinates closing checklist across buyer, seller, lender, notary — tracks doc collection and dates.",
         reads="Deal record", writes="Closing plan + status.",
         tools=["read_crm", "email"],
         tags=["closing", "escrow", "real-estate"],
         vertical="real-estate"),
    dict(id="mortgage_prequal", title="Mortgage Pre-Qual", artifact="agent", stage=CAPTURE, autonomy=AUTO, maturity=2,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="Runs a soft mortgage prequal from buyer inputs; recommends lender panel and expected rate bands.",
         reads="Buyer income + credit + savings", writes="Prequal memo.",
         tools=["lender_apis"],
         tags=["mortgage", "prequal", "real-estate"],
         vertical="real-estate"),
]

MARKETING_AGENCY = [
    dict(id="client_reporting", title="Client Reporting", artifact="agent", stage=ORCHESTRATE, autonomy=AUTO, maturity=3,
         role="writer", mode="scheduled", produces="pdf",
         purpose="Monthly client report: KPIs, wins, spend, next month plan — auto-personalised per client brand.",
         reads="Client accounts data", writes="Report PDF.",
         tools=["ga4_api", "meta_ads_api", "google_ads_api", "write_pdf"],
         tags=["reporting", "client", "agency"],
         vertical="marketing-agency"),
    dict(id="creative_approval_flow", title="Creative Approval Flow", artifact="sidecar", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=2,
         role="connector", mode="event-driven", produces="side_effect",
         purpose="Runs creative through client-approval steps with reminders, version tracking, redlines.",
         reads="Creative asset + client SLA", writes="Approval state.",
         tools=["notion_api", "email"],
         tags=["approval", "creative", "agency"],
         vertical="marketing-agency"),
    dict(id="scope_change_control", title="Scope Change Control", artifact="agent", stage=CAPTURE, autonomy=ASSISTED, maturity=2,
         role="writer", mode="single-shot", produces="markdown_report",
         purpose="Detects scope changes from client messages and drafts change orders with impact analysis.",
         reads="Client threads + SOW", writes="Change order draft.",
         tools=["read_email", "read_sow"],
         tags=["scope", "change-order", "agency"],
         vertical="marketing-agency"),
    dict(id="timesheet_reconciliation", title="Timesheet Reconciliation", artifact="sidecar", stage=CAPTURE, autonomy=AUTO, maturity=2,
         role="worker", mode="scheduled", produces="side_effect",
         purpose="Rolls up team timesheets vs budgets per client; flags overruns before month-end.",
         reads="Timesheets + budgets", writes="Reconciliation table.",
         tools=["timesheet_api", "read_budget"],
         tags=["timesheets", "billing", "agency"],
         vertical="marketing-agency"),
    dict(id="creative_pipeline", title="Creative Pipeline", artifact="agent", stage=ORCHESTRATE, autonomy=ASSISTED, maturity=2,
         role="coordinator", mode="scheduled", produces="markdown_report",
         purpose="Balances creative team capacity vs demand across clients; proposes rebalance and hiring signals.",
         reads="PM board + timesheets", writes="Pipeline plan.",
         tools=["read_pm_board", "timesheet_api"],
         tags=["pipeline", "capacity", "agency"],
         vertical="marketing-agency"),
    dict(id="pitch_deck_generator", title="Pitch Deck Generator", artifact="agent", stage=GENERATE, autonomy=ASSISTED, maturity=2,
         role="writer", mode="single-shot", produces="pptx",
         purpose="Generates a bespoke pitch deck per new-business opportunity from the case-study library.",
         reads="Opportunity brief + case studies", writes="Pitch deck.",
         tools=["case_studies", "write_pptx"],
         tags=["pitch", "new-business", "agency"],
         vertical="marketing-agency"),
]

NIGHTCLUB = [
    dict(id="guest_list_management", title="Guest List Management", artifact="sidecar", stage=CAPTURE, autonomy=AUTO, maturity=2,
         role="worker", mode="event-driven", produces="side_effect",
         purpose="Manages nightly guest lists across sources (social, promoters, VIP): dedup, tier, arrival tracking.",
         reads="RSVP sources", writes="Guest list + tier + status.",
         tools=["door_scanner_api", "crm_upsert"],
         tags=["guest-list", "door", "nightclub"],
         vertical="nightclub"),
    dict(id="bottle_service_pricing", title="Bottle Service Pricing", artifact="agent", stage=GENERATE, autonomy=ASSISTED, maturity=2,
         role="analyst", mode="single-shot", produces="markdown_report",
         purpose="Dynamic pricing recommendations for bottle service by night, promoter, table position — protects floor rate.",
         reads="History + reservations", writes="Pricing plan per night.",
         tools=["read_reservations", "statistical_analysis"],
         tags=["pricing", "bottle-service", "nightclub"],
         vertical="nightclub"),
    dict(id="reservation_handling", title="Reservation Handling", artifact="agent", stage=CAPTURE, autonomy=AUTO, maturity=2,
         role="writer", mode="event-driven", produces="markdown_report",
         purpose="Handles reservation inbounds (WhatsApp, DM, email): qualifies party, quotes, confirms, adds to floor plan.",
         reads="Inbound request", writes="Confirmation + floor plan update.",
         tools=["whatsapp_api", "instagram_api", "reservation_system"],
         tags=["reservations", "nightclub"],
         vertical="nightclub"),
    dict(id="dj_booking_pipeline", title="DJ Booking Pipeline", artifact="agent", stage=GENERATE, autonomy=ASSISTED, maturity=1,
         role="coordinator", mode="single-shot", produces="markdown_report",
         purpose="Plans DJ bookings: shortlist, fee proposals, contract, promo asset request, riders.",
         reads="Season plan + budget", writes="Booking bundle.",
         tools=["contract_templates", "read_budget"],
         tags=["dj", "booking", "nightclub"],
         vertical="nightclub"),
    dict(id="social_night_recap", title="Social Night Recap", artifact="agent", stage=GENERATE, autonomy=AUTO, maturity=2,
         role="writer", mode="event-driven", produces="structured_json",
         purpose="Assembles next-morning night recap posts: highlights, DJ tags, upcoming week — for Instagram + TikTok.",
         reads="Night KPIs + media", writes="Recap posts.",
         tools=["instagram_api", "read_media"],
         tags=["social", "recap", "nightclub"],
         vertical="nightclub"),
    dict(id="incident_book", title="Incident Book", artifact="sidecar", stage=CAPTURE, autonomy=ASSISTED, maturity=2,
         role="worker", mode="event-driven", produces="side_effect",
         purpose="Captures door + floor incidents: refusals, ejections, medical, damage — with time, staff, evidence links.",
         reads="Radio + door log intake", writes="Incident records + weekly digest.",
         tools=["door_scanner_api", "vault_api"],
         tags=["incident", "safety", "nightclub"],
         vertical="nightclub"),
    dict(id="licensing_compliance", title="Licensing Compliance", artifact="agent", stage=ORCHESTRATE, autonomy=LED, maturity=1,
         role="analyst", mode="scheduled", produces="markdown_report",
         purpose="Founder-led. Tracks licences, capacity limits, noise readings, staff certifications; alerts on lapses.",
         reads="Licence registry + logs", writes="Compliance state.",
         tools=["read_registry", "noise_meter_api"],
         tags=["licensing", "compliance", "founder-led", "nightclub"],
         vertical="nightclub"),
    dict(id="bar_inventory", title="Bar Inventory", artifact="sidecar", stage=CAPTURE, autonomy=AUTO, maturity=3,
         role="worker", mode="scheduled", produces="side_effect",
         purpose="Reconciles POS pours vs stock counts; flags shrink, low-stock, forecasts reorder points.",
         reads="POS + stock counts", writes="Shrink report + reorder list.",
         tools=["pos_api"],
         tags=["inventory", "bar", "nightclub"],
         vertical="nightclub"),
]
